export const mockProducts = [
  {
    id: '1',
    name: 'UltraBoost Pro',
    slug: 'ultraboost-pro',
    description: 'Experience ultimate comfort with our flagship running shoe. Features responsive cushioning and a sleek design for both performance and style. Perfect for daily runs and casual wear.',
    price: 189.99,
    comparePrice: 219.99,
    brand: 'SportZone',
    rating: 4.8,
    reviewCount: 125,
    stock: 150,
    tags: ['running', 'comfort', 'bestseller'],
    images: [
      { id: '1', url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800', alt: 'UltraBoost Pro', isPrimary: true },
    ],
    category: { name: 'Shoes', slug: 'shoes' },
    variants: [
      { id: 'v1', size: '10', color: 'Black', colorCode: '#000000', stock: 30 },
      { id: 'v2', size: '11', color: 'Black', colorCode: '#000000', stock: 25 },
      { id: 'v3', size: '10', color: 'White', colorCode: '#FFFFFF', stock: 20 },
    ],
  },
  {
    id: '2',
    name: 'AeroFit Training Tee',
    slug: 'aerofit-training-tee',
    description: 'Lightweight, breathable training tee with moisture-wicking technology. Perfect for intense workouts and everyday comfort.',
    price: 45.99,
    comparePrice: 55.99,
    brand: 'SportZone',
    rating: 4.6,
    reviewCount: 89,
    stock: 200,
    tags: ['training', 'basics', 'breathable'],
    images: [
      { id: '2', url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800', alt: 'AeroFit Training Tee', isPrimary: true },
    ],
    category: { name: 'Clothing', slug: 'clothing' },
    variants: [
      { id: 'v4', size: 'M', color: 'Black', colorCode: '#000000', stock: 50 },
      { id: 'v5', size: 'L', color: 'Black', colorCode: '#000000', stock: 50 },
      { id: 'v6', size: 'M', color: 'White', colorCode: '#FFFFFF', stock: 40 },
    ],
  },
  {
    id: '3',
    name: 'ProRunner Jacket',
    slug: 'prorunner-jacket',
    description: 'Water-resistant running jacket with reflective details. Designed for all-weather running with a lightweight, packable design.',
    price: 129.99,
    comparePrice: 159.99,
    brand: 'SportZone',
    rating: 4.7,
    reviewCount: 67,
    stock: 80,
    tags: ['running', 'jacket', 'weatherproof'],
    images: [
      { id: '3', url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800', alt: 'ProRunner Jacket', isPrimary: true },
    ],
    category: { name: 'Clothing', slug: 'clothing' },
    variants: [
      { id: 'v7', size: 'L', color: 'Navy', colorCode: '#1E3A5F', stock: 20 },
      { id: 'v8', size: 'L', color: 'Black', colorCode: '#000000', stock: 25 },
    ],
  },
  {
    id: '4',
    name: 'Sport Classic Backpack',
    slug: 'sport-classic-backpack',
    description: 'Durable sports backpack with laptop compartment and ventilated shoe pocket. Perfect for gym and travel.',
    price: 79.99,
    brand: 'SportZone',
    rating: 4.5,
    reviewCount: 45,
    stock: 100,
    tags: ['backpack', 'accessories', 'daily'],
    images: [
      { id: '4', url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800', alt: 'Sport Classic Backpack', isPrimary: true },
    ],
    category: { name: 'Accessories', slug: 'accessories' },
    variants: [],
  },
  {
    id: '5',
    name: 'SpeedElite Running Shorts',
    slug: 'speedelite-running-shorts',
    description: 'Ultra-light running shorts with built-in brief and reflective accents. Maximum comfort for runners.',
    price: 59.99,
    comparePrice: 69.99,
    brand: 'SportZone',
    rating: 4.4,
    reviewCount: 78,
    stock: 120,
    tags: ['running', 'shorts', 'lightweight'],
    images: [
      { id: '5', url: 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800', alt: 'SpeedElite Running Shorts', isPrimary: true },
    ],
    category: { name: 'Running', slug: 'running' },
    variants: [
      { id: 'v9', size: 'M', color: 'Black', colorCode: '#000000', stock: 30 },
      { id: 'v10', size: 'L', color: 'Black', colorCode: '#000000', stock: 30 },
    ],
  },
  {
    id: '6',
    name: 'AeroRun Lite',
    slug: 'aerorun-lite',
    description: 'Lightweight racing shoe with responsive cushioning. Designed for speed and performance on race day.',
    price: 149.99,
    comparePrice: 179.99,
    brand: 'SportZone',
    rating: 4.6,
    reviewCount: 92,
    stock: 90,
    tags: ['running', 'racing', 'lightweight'],
    images: [
      { id: '6', url: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800', alt: 'AeroRun Lite', isPrimary: true },
    ],
    category: { name: 'Running', slug: 'running' },
    variants: [
      { id: 'v11', size: '10', color: 'Blue', colorCode: '#0066CC', stock: 25 },
      { id: 'v12', size: '11', color: 'Blue', colorCode: '#0066CC', stock: 20 },
    ],
  },
  {
    id: '7',
    name: 'FlexMove Leggings',
    slug: 'flexmove-leggings',
    description: 'High-performance leggings with 4-way stretch and moisture management. Perfect for yoga, training, or everyday wear.',
    price: 69.99,
    brand: 'SportZone',
    rating: 4.7,
    reviewCount: 156,
    stock: 180,
    tags: ['leggings', 'training', 'yoga'],
    images: [
      { id: '7', url: 'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800', alt: 'FlexMove Leggings', isPrimary: true },
    ],
    category: { name: 'Clothing', slug: 'clothing' },
    variants: [
      { id: 'v13', size: 'S', color: 'Black', colorCode: '#000000', stock: 40 },
      { id: 'v14', size: 'M', color: 'Black', colorCode: '#000000', stock: 50 },
      { id: 'v15', size: 'L', color: 'Black', colorCode: '#000000', stock: 35 },
    ],
  },
  {
    id: '8',
    name: 'PowerGrip Training Gloves',
    slug: 'powergrip-training-gloves',
    description: 'Premium training gloves with wrist support and silicone grip pads. Protect your hands during heavy lifts.',
    price: 34.99,
    brand: 'SportZone',
    rating: 4.3,
    reviewCount: 34,
    stock: 150,
    tags: ['gloves', 'training', 'accessories'],
    images: [
      { id: '8', url: 'https://images.unsplash.com/photo-1583473848882-f9a5c8897d15?w=800', alt: 'PowerGrip Training Gloves', isPrimary: true },
    ],
    category: { name: 'Accessories', slug: 'accessories' },
    variants: [
      { id: 'v16', size: 'M', color: 'Black', colorCode: '#000000', stock: 50 },
      { id: 'v17', size: 'L', color: 'Black', colorCode: '#000000', stock: 50 },
    ],
  },
];

export const mockCategories = [
  { id: '1', name: 'Shoes', slug: 'shoes', description: 'Performance footwear', _count: { products: 25 } },
  { id: '2', name: 'Clothing', slug: 'clothing', description: 'Athletic wear', _count: { products: 18 } },
  { id: '3', name: 'Accessories', slug: 'accessories', description: 'Sports gear', _count: { products: 12 } },
  { id: '4', name: 'Running', slug: 'running', description: 'Running gear', _count: { products: 15 } },
];
